services:
  redis:
    image: redis:7-alpine
    container_name: learning-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    
  mongo:
    image: mongo:7
    container_name: learning-mongo-redis
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: learning_mongo_redis
    volumes:
      - mongo-redis-data:/data/db
  
volumes:
  redis-data:
  mongo-redis-data: